# markdownlint
# https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md

## heading-increment
MD001: true

## heading-style
MD003:
  style: atx

## ul-style
MD004:
  style: dash

## list-indent
MD005: true

## ul-indent
MD007:
  indent: 2
  start_indented: false

## no-trailing-spaces
MD009:
  br_spaces: 2
  list_item_empty_lines: true
  strict: true

## no-hard-tabs
MD010:
  code_blocks: true

## no-reversed-links
MD011: true

## no-multiple-blanks
MD012:
  maximum: 1

## line-length
MD013:
  code_blocks: true
  code_block_line_length: 80
  headings: true
  heading_line_length: 80
  line_length: 80
  tables: true
  strict: false
  stern: true

## commands-show-output
MD014: true

## no-missing-space-atx
MD018: true

## no-multiple-space-atx
MD019: true

## no-missing-space-closed-atx
MD020: true

## no-multiple-space-closed-atx
MD021: true

## blanks-around-headings
MD022:
  lines_above: 1
  lines_below: 1

## heading-start-left
MD023: true

## no-duplicate-heading
MD024:
  allow_different_nesting: true
  siblings_only: true

## single-title
MD025:
  front_matter_title: ^\s*title\s*[:=]
  level: 1

## no-trailing-punctuation
MD026:
  punctuation: .,:;!

## no-multiple-space-blockquote
MD027: true

## no-blanks-blockquote
MD028: true

## ol-prefix
MD029:
  style: one

## list-marker-space
MD030:
  ol_multi: 1
  ol_single: 1
  ul_multi: 1
  ul_single: 1

## blanks-around-fences
MD031:
  list_items: true

## blanks-around-lists
MD032: true

## no-inline-html
MD033:
  allowed_elements: []

## no-bare-urls
MD034: true

## hr-style
MD035:
  style: ---

## no-emphasis-as-heading
MD036:
  punctuation: .:,;!

## no-space-in-emphasis
MD037: true

## no-space-in-code
MD038: true

## no-space-in-links
MD039: true
